# Generated by Django 4.1.7 on 2023-06-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_reviewrating"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReviewRating",
        ),
    ]
